services:
  privoxy:
    build: .
    container_name: privoxy
    ports:
      - "${PRIVOXY_PORT:-8118}:8118"
      - "${SOCKS5_PORT:-5003}:5003"
    environment:
      - SOCKS5_PORT=${SOCKS5_PORT:-5003}
    restart: unless-stopped